version: '3.1'

services:
  web:
    restart: always
    image: go-mysql-crud
    ports:
      - 8005:8005
    links:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "DB_NAME=go-mysql-crud"
      - "DB_PASS=admin"
      - "DB_USER=dbuser"
  
  mysql:
    image: arm64v8/mysql:oracle
    # image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=go-mysql-crud
      - MYSQL_PASSWORD=admin
      - MYSQL_USER=dbuser
    # volumes:
    #   - /mysql:/var/lib/mysql
    
